LOCAL_PATH := device/realme/luigi

PRODUCT_DEVICE := luigi
PRODUCT_NAME := twrp_luigi
PRODUCT_BRAND := realme
PRODUCT_MODEL := RMX3660
PRODUCT_MANUFACTURER := realme

PRODUCT_SHIPPING_API_LEVEL := 35

TW_INCLUDE_FASTBOOTD := true

TW_NO_DECRYPT := true
TW_INCLUDE_CRYPTO := false
